### ISSUE TITLE
ResXManager 1.42.3648 crashes on VS 2017 load

### ISSUE THREAD

**Issue by SylwesterZarebski** [dotnet/ResXResourceManager#331]
After updating to 1.42.3648 extension crashes at VS 2017 start.
VS 2017 15.9.20, will try to update to newest 15.9.24.
Activity.xml log entry:
```
SetSite failed for package [VsPackage]Source: 'mscorlib' Description: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetEnumerator()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.ComponentModel.Composition.Hosting.ComposablePartCatalogCollection.&lt;&gt;c__DisplayClass8_0.&lt;Add&gt;b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at System.ComponentModel.Composition.Hosting.ComposablePartCatalogCollection.RaiseChangingEvent(Lazy`1 addedDefinitions, Lazy`1 removedDefinitions, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ComposablePartCatalogCollection.Add(ComposablePartCatalog item)
   at ResXManager.VSIX.VsPackage.FillCatalog()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ResXManager.VSIX.VsPackage.&lt;InitializeAsync&gt;d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass16_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__78.MoveNext()</description>
```

**Comment by SylwesterZarebski** [comment]
I've checked VS 2019, and there are no crash. Maybe 1.42 reference libraries not existing in VS 2017?

**Comment by SylwesterZarebski** [comment]
After updating VS 2017 to 15.9.24, there are no crash. Nothing in VS changelog indicates what could be a problem.
Closing this issue.

**Comment by mikemorton** [comment]
I'm experiencing this issue with 15.9.16 as well.

**Comment by tom-englert** [comment]
@mikemorton these are all problems with the VSIX installer, not the component. 
Did you check all described in https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Troubleshooting.md?

**Comment by SylwesterZarebski** [comment]
@tom-englert : Troubleshooting do not goes beyond duplicates, and this is not about duplicates. There is some code in VSIX package which references some library, which is not available in older versions of VS 2017. Then above error shows.
Without playing with source compiling there is no way to find what is real culprit.

**Comment by tom-englert** [comment]
@SylwesterZarebski So what was the outcome of your evalutation?

**Comment by SylwesterZarebski** [comment]
I did not play with source, sorry, i do not have required knowledge about VS extensions to look under the surface :-(.

**Comment by tom-englert** [comment]
So just because updating VS fixed the problem, it does not mean it would not have worked with the older version. 
Updating VS also clears the VSIX caches, which fixes the problem.

**Comment by SylwesterZarebski** [comment]
If by clearing caches You meant MEF cache, i've checked that before and it did not work. I've used extension _Clear MEF component cache_ (by Mads Kristensen).
