### ISSUE TITLE
InternalGetValue Exceptions 

### ISSUE THREAD

**Issue by Samit-BTE** [dotnet/ResXResourceManager#352]
Keep Throwing error dialog every time open resource file or open xamal files. 

![image](https://user-images.githubusercontent.com/63873262/91585829-8d7a8c00-e922-11ea-9642-608368917cb9.png)

Error With Xamarin project. 

VS2019 16.7.2
Xamarin 4.8.0.1269
ResXResourceManager: 1.43.3735

Exception Log
```
Error: System.Runtime.InteropServices.COMException (0x8001010E): InternalGetValue must be called on the UI thread.
   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)
   at ResXManager.VSIX.DteConfiguration.InternalGetValue[T](T defaultValue, String key)
   at ResXManager.Model.ConfigurationBase.GetValue[T](T defaultValue, String key)
   at ResXManager.Model.ConfigurationBase.GetProperty[T](String key, PropertyInfo propertyInfo)
   at ResXManager.Model.Configuration.get_NeutralResourcesLanguage()
   at ResXManager.Model.ProjectFileExtensions.GetCultureKey(ProjectFile projectFile, IConfiguration configuration)
   at ResXManager.Model.ResourceEntity.<>c__DisplayClass44_0.<GetResourceLanguages>b__0(ProjectFile file)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ResXManager.Model.ResourceEntity.GetResourceLanguages(IEnumerable`1 files, DuplicateKeyHandling duplicateKeyHandling)
   at ResXManager.Model.ResourceEntity..ctor(ResourceManager container, String projectName, String baseName, String directoryName, ICollection`1 files, DuplicateKeyHandling duplicateKeyHandling)
   at ResXManager.Model.ResourceManager.<>c__DisplayClass52_0.<LoadEntitiesAsync>g__Load|2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ResXManager.Model.ResourceManager.<LoadEntitiesAsync>d__52.MoveNext()
Error: System.Runtime.InteropServices.COMException (0x8001010E): InternalGetValue must be called on the UI thread.
   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)
   at ResXManager.VSIX.DteConfiguration.InternalGetValue[T](T defaultValue, String key)
   at ResXManager.Model.ConfigurationBase.GetValue[T](T defaultValue, String key)
   at ResXManager.Model.ConfigurationBase.GetProperty[T](String key, PropertyInfo propertyInfo)
   at ResXManager.Model.Configuration.get_NeutralResourcesLanguage()
   at ResXManager.Model.ProjectFileExtensions.GetCultureKey(ProjectFile projectFile, IConfiguration configuration)
   at ResXManager.Model.ResourceEntity.<>c__DisplayClass44_0.<GetResourceLanguages>b__0(ProjectFile file)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ResXManager.Model.ResourceEntity.GetResourceLanguages(IEnumerable`1 files, DuplicateKeyHandling duplicateKeyHandling)
   at ResXManager.Model.ResourceEntity..ctor(ResourceManager container, String projectName, String baseName, String directoryName, ICollection`1 files, DuplicateKeyHandling duplicateKeyHandling)
   at ResXManager.Model.ResourceManager.<>c__DisplayClass52_0.<LoadEntitiesAsync>g__Load|2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ResXManager.Model.ResourceManager.<LoadEntitiesAsync>d__52.MoveNext()
Error: System.Runtime.InteropServices.COMException (0x8001010E): InternalGetValue must be called on the UI thread.
   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)
   at ResXManager.VSIX.DteConfiguration.InternalGetValue[T](T defaultValue, String key)
   at ResXManager.Model.ConfigurationBase.GetValue[T](T defaultValue, String key)
   at ResXManager.Model.ConfigurationBase.GetProperty[T](String key, PropertyInfo propertyInfo)
   at ResXManager.Model.Configuration.get_NeutralResourcesLanguage()
   at ResXManager.Model.ProjectFileExtensions.GetCultureKey(ProjectFile projectFile, IConfiguration configuration)
   at ResXManager.Model.ResourceEntity.<>c__DisplayClass44_0.<GetResourceLanguages>b__0(ProjectFile file)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ResXManager.Model.ResourceEntity.GetResourceLanguages(IEnumerable`1 files, DuplicateKeyHandling duplicateKeyHandling)
   at ResXManager.Model.ResourceEntity..ctor(ResourceManager container, String projectName, String baseName, String directoryName, ICollection`1 files, DuplicateKeyHandling duplicateKeyHandling)
   at ResXManager.Model.ResourceManager.<>c__DisplayClass52_0.<LoadEntitiesAsync>g__Load|2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ResXManager.Model.ResourceManager.<LoadEntitiesAsync>d__52.MoveNext()
```

**Comment by matheus-inacio** [comment]
Yep, i'm facing the exact same error on my UWP project.

I've tried to reinstall but the error still happens.
