### ISSUE TITLE
ResX not inserting resource, get exception (VS 2019)

### ISSUE THREAD

**Issue by lkeeble** [dotnet/ResXResourceManager#359]
Hi, I right click on a string and select "Move to Resource". Nothing seems to happen. In the Output window for ResX Resource Manager I see error messages as shown below. It worked fine for months - until now. I have tried uninstalling and reinstalling, it doesn't fix the issue.
```
Error: System.Runtime.InteropServices.COMException (0x80004005): Project unavailable.
   at EnvDTE.ProjectItem.get_ContainingProject()
   at ResXManager.VSIX.Refactorings.<>c.<IsInProject>b__8_0(ProjectItem item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value)
   at ResXManager.VSIX.Refactorings.IsInProject(ResourceEntity entity, Project project)
   at ResXManager.VSIX.Refactorings.<>c__DisplayClass6_0.<GetResourceEntriesFromProject>b__0(ResourceEntity entity)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection)
   at ResXManager.VSIX.Refactorings.<MoveToResourceAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ResXManager.VSIX.VsPackage.<MoveToResource>d__36.MoveNext()
ResX Resource Manager loaded.
Home: https://github.com/dotnet/ResXResourceManager
Report issues: https://github.com/dotnet/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Assembly location: c:\users\(username removed)\appdata\local\microsoft\visualstudio\16.0_eca5947c\extensions\zhrolc5b.ewk
Version: 1.46.3794.0
```

**Comment by tom-englert** [comment]
`COMException (0x80004005): Project unavailable. at EnvDTE.ProjectItem.get_ContainingProject()` 
this is thrown from VisualStudio, so this is a problem with the current project not fully loaded. Also sometimes VS loses track of it's internal items, and restarting VisualStudio fixes this. If this problem persists, report it to Microsoft.

**Comment by tom-englert** [comment]
Also maybe you have some invalid items in the project. I tried to make traversing the items more robust.

**Comment by lkeeble** [comment]
OK, thanks for looking into it. It's not fixed by restarting VS unfortunately.

**Comment by tom-englert** [comment]
Can you try the latest build?
https://www.vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a

**Comment by lkeeble** [comment]
After uninstalling and installing the latest build (1.46.3812.0)  I get the following:

1. Pick a string and right click, select "Move to Resource"
2. The ResX ResourceManager pops up. 
3. I select the resource file, "New Entry" and click OK. 
4. The string is replaced with the Resource in the code and all appears well. 
5. After a short while a compile error is shown (red squiggly) under the resource in the code. On checking the ResX file I see that the resource was not added.

Note: I occasionally saw the above behavior prior to using the new build. It seems to be somewhat random whether or not the ResX manager pops up, or just is not shown at all. It's my impression that restarting VS will make the ResX manager more likely to appear.

Thanks for your help with this.
