### ISSUE TITLE
Cant see files in ResourceManager.

### ISSUE THREAD

**Issue by Aangbaeck** [dotnet/ResXResourceManager#372]
I get this error when i try to start ResXManager. I cant see the files on the side and it's not availible when i right-click in VS. When i start from the tools menu the windows open but it can't see the ResX-files. It's the same error when running the stand-alone version.

VSIX VS-Error:
```
ResX Resource Manager loaded.
Home: https://github.com/dotnet/ResXResourceManager
Report issues: https://github.com/dotnet/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Assembly location: c:\users\bjak\appdata\local\microsoft\visualstudio\16.0_e0bf4fde\extensions\mmxp1bha.oxb
Version: 1.48.3862.0
.NET Framework Version: 528040 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
Switch.System.Windows.Baml2006.AppendLocalAssemblyVersionForSourceUri=True (https://github.com/Microsoft/dotnet/blob/master/releases/net472/dotnet472-changes.md#wpf)
Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at ResXManager.Model.XmlConfiguration.<>c.<GetValue>b__10_3(XText node) in D:\a\1\s\src\ResXManager.Model\XmlConfiguration.cs:line 105
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at ResXManager.Model.XmlConfiguration.GetValue(String key, String defaultValue) in D:\a\1\s\src\ResXManager.Model\XmlConfiguration.cs:line 100
   at ResXManager.Model.ConfigurationBase.InternalGetValue[T](T defaultValue, String key) in D:\a\1\s\src\ResXManager.Model\ConfigurationBase.cs:line 111
   at ResXManager.VSIX.DteConfiguration.InternalGetValue[T](T defaultValue, String key) in D:\a\1\s\src\ResXManager.VSIX\DteConfiguration.cs:line 55
   at ResXManager.Model.ConfigurationBase.GetValue[T](T defaultValue, String key) in D:\a\1\s\src\ResXManager.Model\ConfigurationBase.cs:line 99
   at ResXManager.Model.ConfigurationBase.GetProperty[T](String key, PropertyInfo propertyInfo) in D:\a\1\s\src\ResXManager.Model\ConfigurationBase.cs:line 71
   at ResXManager.Model.FileFilter..ctor(Configuration configuration) in D:\a\1\s\src\ResXManager.Model\FileFilter.cs:line 16
   at ResXManager.VSIX.DteSourceFilesProvider.get_DteSourceFiles() in D:\a\1\s\src\ResXManager.VSIX\DteSourceFilesProvider.cs:line 57
   at ResXManager.VSIX.DteSourceFilesProvider.<GetSourceFilesAsync>d__4.MoveNext() in D:\a\1\s\src\ResXManager.VSIX\DteSourceFilesProvider.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ResXManager.View.Visuals.ResourceViewModel.<ReloadAsync>d__94.MoveNext() in D:\a\1\s\src\ResXManager.View\Visuals\ResourceViewModel.cs:line 510
Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at ResXManager.Model.XmlConfiguration.<>c.<GetValue>b__10_3(XText node) in D:\a\1\s\src\ResXManager.Model\XmlConfiguration.cs:line 105
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at ResXManager.Model.XmlConfiguration.GetValue(String key, String defaultValue) in D:\a\1\s\src\ResXManager.Model\XmlConfiguration.cs:line 100
   at ResXManager.Model.ConfigurationBase.InternalGetValue[T](T defaultValue, String key) in D:\a\1\s\src\ResXManager.Model\ConfigurationBase.cs:line 111
   at ResXManager.VSIX.DteConfiguration.InternalGetValue[T](T defaultValue, String key) in D:\a\1\s\src\ResXManager.VSIX\DteConfiguration.cs:line 55
   at ResXManager.Model.ConfigurationBase.GetValue[T](T defaultValue, String key) in D:\a\1\s\src\ResXManager.Model\ConfigurationBase.cs:line 99
   at ResXManager.Model.ConfigurationBase.GetProperty[T](String key, PropertyInfo propertyInfo) in D:\a\1\s\src\ResXManager.Model\ConfigurationBase.cs:line 71
   at ResXManager.Model.FileFilter..ctor(Configuration configuration) in D:\a\1\s\src\ResXManager.Model\FileFilter.cs:line 16
   at ResXManager.VSIX.DteSourceFilesProvider.get_DteSourceFiles() in D:\a\1\s\src\ResXManager.VSIX\DteSourceFilesProvider.cs:line 57
   at ResXManager.VSIX.DteSourceFilesProvider.<GetSourceFilesAsync>d__4.MoveNext() in D:\a\1\s\src\ResXManager.VSIX\DteSourceFilesProvider.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ResXManager.View.Visuals.ResourceViewModel.<ReloadAsync>d__94.MoveNext() in D:\a\1\s\src\ResXManager.View\Visuals\ResourceViewModel.cs:line 510

Standalone version:
09:32	Started
09:32	ResX Resource Manager loaded.
Home: https://github.com/dotnet/ResXResourceManager
Report issues: https://github.com/dotnet/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
09:32	Assembly location: C:\Users\BJAK\AppData\Local\Apps\2.0\W81LJ7BJ.CN9\HJ6T73VX.XWO\resx..ager_b1f65a3233f3cf33_0001.0030_268d8da57f6d9954
09:32	Version: 1.48.3862.0
09:32	Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at ResXManager.Model.XmlConfiguration.<>c.<GetValue>b__10_3(XText node)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at ResXManager.Model.XmlConfiguration.GetValue(String key, String defaultValue)
   at ResXManager.Model.ConfigurationBase.InternalGetValue[T](T defaultValue, String key)
   at ResXManager.Model.ConfigurationBase.GetValue[T](T defaultValue, String key)
   at ResXManager.Model.ConfigurationBase.GetProperty[T](String key, PropertyInfo propertyInfo)
   at ResXManager.Model.FileFilter..ctor(Configuration configuration)
   at ResXManager.SourceFilesProvider.<GetSourceFilesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ResXManager.View.Visuals.ResourceViewModel.<ReloadAsync>d__94.MoveNext()
```

**Comment by Aangbaeck** [comment]
I have tried to Uninstall/Reinstall both version multiple times. Also tried removing duplicates. Followed troubleshooting and changed Regedit. .Nothing helped. 😢 I really need this to work for the project I'm working on has huge amounts of ResX files that needs translating and ResManager is the best.

**Comment by tom-englert** [comment]
Looks like `%localappdata%\tom-englert.de\ResXManager\Configuration.xml` is broken. 
You can delete or repair it...

**Comment by Aangbaeck** [comment]
Brilliant, that solved the issue for me. I wonder why it broke?! I would not have figured that out just by reading the stacktrace. Well, thanks anyway. Great work by the way.
