### ISSUE TITLE
VS2022 throws an error "The 'VsPackage' package did not load correctly"

### ISSUE THREAD

**Issue by anddrzejb** [dotnet/ResXResourceManager#425]
**Describe the bug**
When starting VS 2022 I get this error message:
![image](https://user-images.githubusercontent.com/6518006/133428270-6da281d9-a881-4f3f-9ffa-ebdd3e248bf5.png)

The significant part of the `ActivityLog.xml`:
```log
CreateInstance failed for package [VsPackage]Source: 'mscorlib' Description: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at ResXManager.VSIX.CustomToolRunner..ctor()
   at ResXManager.VSIX.VsPackage..ctor() in D:\a\1\s\src\ResXManager.VSIX\VSPackage.cs:line 61
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)System.IO.FileNotFoundException: Could not load file or assembly 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at ResXManager.VSIX.CustomToolRunner..ctor()
   at ResXManager.VSIX.VsPackage..ctor() in D:\a\1\s\src\ResXManager.VSIX\VSPackage.cs:line 61

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```
`ResXResourceManager` does not open. The same error pops as on the screenshot. 

**To Reproduce**
New installation of VS 2022 ver. 17.0.0 Preview 4.0

**Expected behavior**
No error. `ResXResourceManager` should show up.

**Comment by anddrzejb** [comment]
A very similar bug (maybe the same since it also complains about missing `EnvDTE` assembly) was solved by @conficient in [his fix](https://github.com/madskristensen/AddAnyFile/issues/87#issuecomment-905421120) for [AddAnyFile extension issue](https://github.com/madskristensen/AddAnyFile/issues/87). Maybe the same solution can be applied here.

**Comment by tom-englert** [comment]
Can't reproduce this. What version of resx-manager are you trying to use?

**Comment by anddrzejb** [comment]
I downloaded the fresh version from [visual studio market](https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager). Version that I have is 1.56.4540.0.

**Comment by tom-englert** [comment]
Can you try the latest build from https://www.vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a
I already did some refactoring for VS2022

**Comment by anddrzejb** [comment]
Works! Thanks @tom-englert!

**Comment by tom-englert** [comment]
OK, I'll make an official release from this

**Comment by nitz** [comment]
On VS `16.11.3`, version `1.60.4596.0` (the current latest on the marketplace) was giving me this issue too, but `1.60.4597.0` from vsixgallery fixed it for me as well!

**Comment by tom-englert** [comment]
@nitz this is just the ubiquitous Vsix installer bug, where re- installing fixes the corrupted cache.

**Comment by nitz** [comment]
Figures it should be something so silly! Thanks a heap :)
