### ISSUE TITLE
Visual Studio crashes after opening ResXManager and creating a Git branch

### ISSUE THREAD

**Issue by daze99** [dotnet/ResXResourceManager#505]
When I create a new Git branch after I opened ResXManager Visual Studio crashes and restarts. After the restart Visual Studio reports that ResXManager caused a crash. If ResXManager was never opened or is not installed the branch can be created.

- Start Visual Studio 2022
- Load a project with a Git repository
- Open ResXManager
- Create a new branch (menu _Git -> New branch..._)

Uninstalling ResXManager solves the issue.

**Comment by tom-englert** [comment]
@daze99 I can't reproduce this; I can create and delete branches without problems.

Please attach the error log and stack trace, and the exact Visual Studio version.

**Comment by daze99** [comment]
Faulting application name: devenv.exe, version: 17.3.32929.385, time stamp: 0x63364fdf
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2130, time stamp: 0xb0fac6c9
Exception code: 0xe0434352
Fault offset: 0x000000000002cd29
Faulting process ID: 0x3f64
Faulting application start time: 0x01d8f034dd7f3d57
Faulting application path: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 585a858c-1f23-4c24-ae00-0216400e18fa
Faulting package full name: 
Faulting package-relative application ID: 

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at TomsToolbox.Wpf.PresentationFrameworkExtensions.GetPhysicalPixelSize(System.Windows.FrameworkElement)
   at TomsToolbox.Wpf.TextBlockHelper.EvaluateIsTextTrimmed(System.Windows.Controls.TextBlock)
   at TomsToolbox.Wpf.TextBlockHelper.UpdateIsTextTrimmed(System.Windows.Controls.TextBlock)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.FrameworkElement.OnRenderSizeChanged(System.Windows.SizeChangedInfo)
   at System.Windows.ContextLayoutManager.fireSizeChangedEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
