### ISSUE TITLE
I have issue in ResxManager not Loaded in vs2022

### ISSUE THREAD

**Issue by mjjalala** [dotnet/ResXResourceManager#534]
**Important**
Read https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Troubleshooting.md first.
Problems listed there are bugs in Visual Studio and should be reported to Microsoft, not here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Comment by tom-englert** [comment]
Is there any message in the output pane?

**Comment by soundcrime** [comment]
I experience same issue. When a project has WinForms forms in it, it will have an error in output and context menu option will be lost. I would like to load another, regular resource file in project that is "valid", but cannot do that in VS or in stand-alone app.

`Error: System.InvalidOperationException: C:\MyProject\MyForm.resx is not a valid RESX resource file: Not all entries have a value attribute.
   at ResXManager.Model.ResourceLanguage.Node..ctor(ResourceLanguage owner, XElement element) in D:\a\1\s\src\ResXManager.Model\ResourceLanguage.cs:line 513
   at ResXManager.Model.ResourceLanguage.<UpdateNodes>b__15_0(XElement item) in D:\a\1\s\src\ResXManager.Model\ResourceLanguage.cs:line 88
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ResXManager.Model.ResourceLanguage.UpdateNodes(DuplicateKeyHandling duplicateKeyHandling) in D:\a\1\s\src\ResXManager.Model\ResourceLanguage.cs:line 86
   at ResXManager.Model.ResourceEntity.<>c__DisplayClass52_0.<GetResourceLanguages>b__2(<>f__AnonymousType0`2 <>h__TransparentIdentifier0) in D:\a\1\s\src\ResXManager.Model\ResourceEntity.cs:line 302
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ResXManager.Model.ResourceEntity.GetResourceLanguages(IEnumerable`1 files, CultureInfo neutralResourcesLanguage, DuplicateKeyHandling duplicateKeyHandling) in D:\a\1\s\src\ResXManager.Model\ResourceEntity.cs:line 306
   at ResXManager.Model.ResourceEntity..ctor(ResourceManager container, String projectName, String baseName, String directoryName, ICollection`1 files, CultureInfo neutralResourcesLanguage, DuplicateKeyHandling duplicateKeyHandling) in D:\a\1\s\src\ResXManager.Model\ResourceEntity.cs:line 35
   at ResXManager.Model.ResourceManager.<>c__DisplayClass63_0.<LoadEntitiesAsync>g__Load|2() in D:\a\1\s\src\ResXManager.Model\ResourceManager.cs:line 242
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ResXManager.Model.ResourceManager.<LoadEntitiesAsync>d__63.MoveNext() in D:\a\1\s\src\ResXManager.Model\ResourceManager.cs:line 255`

**Comment by tom-englert** [comment]
What is not clear about this error message?
`Error: System.InvalidOperationException: C:\MyProject\MyForm.resx is not a valid RESX resource file: Not all entries have a value attribute`

**Comment by tom-englert** [comment]
It works very well with WinForms, that's what I initially designed it for 10 years ago.

However it stops at corrupt .resx files, since it's designed to verify and show all resources.

When you have fixed the corrupt file it will start working again.

**Comment by tom-englert** [comment]
@soundcrime @mjjalala still any issues with this?

**Comment by soundcrime** [comment]
We are using components by Infragistics, and it creates <Value> tags (with capital "V") in resx files. If replaced to <value>, the tool starts working.
I replaced tags in hundreds of forms, then was able to load and change common resource files which are used by not only one form, then reverted all these form specific resource files.
At least for me, ResxManager would really benefit from opening just one resx file, not all of them in a folder.

**Comment by tom-englert** [comment]
To edit a single file, just use the default built-in editor.
