### ISSUE TITLE
Support for custom, non-standard culture codes

### ISSUE THREAD

**Issue by randarp** [dotnet/ResXResourceManager#637]
**Is your feature request related to a problem? Please describe.**
Our team cannot use ResXResourceManager out of the box. The problem is our solution gets the following error.

```
3:09 PM	Error: System.InvalidOperationException: Error parsing language: qps-loc
   at ResXManager.Infrastructure.ExtensionMethods.ToCulture(String cultureKeyName)
   at ResXManager.Model.ProjectFileExtensions.GetCultureKey(ProjectFile projectFile, CultureInfo neutralResourcesLanguage)
   at ResXManager.Model.ResourceEntity.<>c__DisplayClass52_0.<GetResourceLanguages>b__0(ProjectFile file)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
```

This happens because we have a culture code called qps-loc. These translations are given to us by Transifex (https://www.transifex.com). It is a "pseudo language" with strings like 

A_GROUP_WITH_THIS_DISPLAY_NAME_ALREADY_EXISTS_PLEASE_ENTER_A_DIFFERENT_NAME
[Ȧ ɠřǿŭƥ ẇīŧħ ŧħīş ḓīşƥŀȧẏ ƞȧḿḗ ȧŀřḗȧḓẏ ḗẋīşŧş. Ƥŀḗȧşḗ ḗƞŧḗř ȧ ḓīƒƒḗřḗƞŧ ƞȧḿḗ. ΰ ǲϰϰǋǅ 鶱ϖς鶱]

When QA switches to that language, we can quickly see any string that has not been translated in the UI. A very useful testing tool.

**Describe the solution you'd like**
I would like the ability to pass in custom culture codes. e.g. An AppSetting value or configuration that allows me to add cultures that are added to the list of proper culture codes. 

**Describe alternatives you've considered**
Our only solution is to remove all files, like CommonStrings.qps-ploc.resx, from the solution, every time we want to use your tool. This is time-consuming (as there are 60+ files) and will then leave the orphan strings that are removed from other files.

**Comment by randarp** [comment]
Thanks @tom-englert. Out of the 60+ pseudo files, there one 1 named PortfolioView.qps-loc. I didn't notice the one character difference.
