### ISSUE TITLE
VS extension 1.88 fails to load in VS2017

### ISSUE THREAD

**Issue by roimvsao** [dotnet/ResXResourceManager#669]
```
ResXResourceManager extension for VisualStudio 2017 fails to load starting from version 1.88. 
VisualStudio reports: The 'VsPackage' package did not load correctly and fails to open the extension window.
Previous version were loading ok. Same version 1.88 works ok on VS2022
Activity log content:
<entry>
    <record>1518</record>
    <time>2024/10/15 05:41:15.997</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [VsPackage]Source: &apos;mscorlib&apos; Description: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information
;System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information
;   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at TomsToolbox.Composition.MetadataReader.Read(Assembly assembly)
   at System.Linq.Enumerable.&lt;SelectManyIterator&gt;d__17`2.MoveNext()
   at TomsToolbox.Composition.Ninject.ExtensionMethods.BindExports(IKernel kernel, IEnumerable`1 exportInfos)
   at TomsToolbox.Composition.Ninject.ExtensionMethods.BindExports(IKernel kernel, IEnumerable`1 assemblies)
   at ResXManager.VSIX.VsPackage.FillCatalog()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ResXManager.VSIX.VsPackage.&lt;InitializeAsync&gt;d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass17_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.ThreadingTools.&lt;WithCancellationSlow&gt;d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask.Join(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.Join(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Shell.VsTaskLibraryHelper.&lt;&gt;c__DisplayClass33_1`1.&lt;AsVsTask&gt;b__3()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
   at Microsoft.VisualStudio.Services.VsTask.GetResult()</description>
    <guid>{43B35FE0-1F30-48DE-887A-68256474202A}</guid>
    <hr>80131602</hr>
    <errorinfo></errorinfo>
  </entry>
```

**Comment by tom-englert** [comment]
I don't have old VS versions installed, can you debug this and provide a fix?

**Comment by Untherxadyus** [comment]
I'm having the same issue, just today I updated Visual Studio 2017 and suddenly the extension stopped loading.
